var list_name = document.getElementById("list_name")
var list1 = document.getElementById("first")
var list2 = document.getElementById("second")
var no = document.getElementById("no_item")
var img = document.getElementsByClassName("img")
var iname = document.getElementsByClassName("i-name")
var iprice = document.getElementsByClassName("i-price")
var item2 = document.getElementsByClassName("item2")
var item_theme
var item_code = new Array(8)
item = location.href.split("?")
switch (item[1]) {
    case "FOUNDATION":
        item_theme = "FOUNDATION&CUSHION"
        list_name.innerHTML = "FOUNDATION&CUSHION"
        item_code[0] = "FC_C1"
        img[0].src = "리스트이미지/쿠션1.jpg"
        iname[0].innerHTML = "모이스쳐 쿠션"
        iprice[0].innerHTML = "35,000원"
        item_code[1] = "FC_C2"
        img[1].src = "리스트이미지/쿠션2.jpg"
        iname[1].innerHTML = "바바파파에디션 쿠션"
        iprice[1].innerHTML = "40,000원"
        item_code[2] = "FC_F1"
        img[2].src = "리스트이미지/파운데이션1.jpg"
        iname[2].innerHTML = "워터풀 파운데이션"
        iprice[2].innerHTML = "43,000원"
        item_code[3] = "FC_F2"
        img[3].src = "리스트이미지/파운데이션2.jpg"
        iname[3].innerHTML = "매트핏 파운데이션"
        iprice[3].innerHTML = "43,000원"
        item_code[4] = "FC_F3"
        img[4].src = "리스트이미지/파운데이션3.jpg"
        iname[4].innerHTML = "리퀴드 파운데이션"
        iprice[4].innerHTML = "39,000원"
        item_code[5] = "FC_F4"
        img[5].src = "리스트이미지/파운데이션4.jpg"
        iname[5].innerHTML = "멜팅 파운데이션"
        iprice[5].innerHTML = "37,000원"
        item2[2].style.display = "none"
        item2[3].style.display = "none"
        break;
    case "CONCEALER":
        item_theme = "CONCEALER"
        list_name.innerHTML = "CONCEALER"
        list2.style.display = "none"
        item_code[0]="C_C1"
        img[0].src = "리스트이미지/컨실러1.jpg"
        iname[0].innerHTML = "풀커버 컨실러"
        iprice[0].innerHTML = "19.000원"
        item_code[1]="C_C2"
        img[1].src = "리스트이미지/컨실러2.jpg"
        iname[1].innerHTML = "페이스 튜닝 컨실러"
        iprice[1].innerHTML = "28.000원"       
        item_code[2]="C_C3"
        img[2].src = "리스트이미지/컨실러3.jpg"
        iname[2].innerHTML = "팟 컨실러"
        iprice[2].innerHTML = "25.000원"
        item_code[3]="C_C4"
        img[3].src = "리스트이미지/컨실러4.jpg"
        iname[3].innerHTML = "워터풀 컨실러"
        iprice[3].innerHTML = "25.000원"
        break;
    case "POWDER":
        item_theme = "POWDER&PACT"
        list_name.innerHTML = "POWDER&PACT"
        item_code[0]="P_P1"
        img[0].src = "리스트이미지/팩트1.jpg"
        iname[0].innerHTML = "세범 팩트"
        iprice[0].innerHTML = "33.000원"
        item_code[1]="P_P2"
        img[1].src = "리스트이미지/팩트2.jpg"
        iname[1].innerHTML = "스킨 핏 파우더 팩트"
        iprice[1].innerHTML = "35.000원"
        item_code[2]="P_P3"
        img[2].src = "리스트이미지/파우더1.jpg"
        iname[2].innerHTML = "루스 파우더"
        iprice[2].innerHTML = "40.000원"
        item_code[3]="P_P4"
        img[3].src = "리스트이미지/파우더2.jpg"
        iname[3].innerHTML = "블로팅 파우더"
        iprice[3].innerHTML = "35.000원"
        img[4].src = "리스트이미지/파우더3.jpg"
        iname[4].innerHTML = "블러 세팅 루스 파우더"
        iprice[4].innerHTML = "SOLD OUT"
        iprice[4].style.color = "red"
        iprice[4].style.fontWeight = "bold"
        img[5].src = "리스트이미지/팩트4.jpg"
        iname[5].innerHTML = "프라이머 세팅 파우더"
        iprice[5].innerHTML = "SOLD OUT"
        iprice[5].style.color = "red"
        iprice[5].style.fontWeight = "bold"
        item2[2].style.display = "none"
        item2[3].style.display = "none"
        break;
    case "EYELINER":
        item_theme = "EYELINER"
        list_name.innerHTML = "EYELINER"
        item_code[0]="E_E1"
        img[0].src = "메인이미지/뉴2.png"
        iname[0].innerHTML = "펜 아이라이너"
        iprice[0].innerHTML = "45,000원"
        item_code[1]="E_E2"
        img[1].src = "메인이미지/뉴3.png"
        iname[1].innerHTML = "글리터 아이라이너"
        iprice[1].innerHTML = "33,000원"
        item_code[2]="E_E3"
        img[2].src = "메인이미지/베스트4.png"
        iname[2].innerHTML = "오토젤 아이라이너"
        iprice[2].innerHTML = "81,000원"
        item_code[3]="E_E4"
        img[3].src = "리스트이미지/아이라이너1.jpg"
        iname[3].innerHTML = "젤 아이라이너"
        iprice[3].innerHTML = "27,000원"
        item_code[4]="E_E5"
        img[4].src = "리스트이미지/아이라이너2.jpg"
        iname[4].innerHTML = "리퀴드 아이라이너"
        iprice[4].innerHTML = "SOLD OUT"
        iprice[4].style.color = "red"
        iprice[4].style.fontWeight = "bold"
        item_code[5]="E_E6"
        img[5].src = "리스트이미지/아이라이너3.jpg"
        iname[5].innerHTML = "펜슬 아이라이너"
        iprice[5].innerHTML = "SOLD OUT"
        iprice[5].style.color = "red"
        iprice[5].style.fontWeight = "bold"
        item2[2].style.display = "none"
        item2[3].style.display = "none"
        break;
    case "EYESHADOW":
        item_theme = "EYESHADOW"
        list_name.innerHTML = "EYESHADOW"
        item_code[0]="E_S1"
        img[0].src = "메인이미지/베스트1.png"
        iname[0].innerHTML = "섀도우"
        iprice[0].innerHTML = "45,000원"
        item_code[1]="E_S2"
        img[1].src = "리스트이미지/섀도우1.jpg"
        iname[1].innerHTML = "스틱 섀도우"
        iprice[1].innerHTML = "40,000원"
        item_code[2]="E_S3"
        img[2].src = "리스트이미지/섀도우2.jpg"
        iname[2].innerHTML = "9구 섀도우 팔레트"
        iprice[2].innerHTML = "90,000원"
        item_code[3]="E_S4"
        img[3].src = "리스트이미지/섀도우3.jpg"
        iname[3].innerHTML = "80구 섀도우 팔레트"
        iprice[3].innerHTML = "75,000원"
        item_code[4]="E_S5"
        img[4].src = "리스트이미지/섀도우4.jpg"
        iname[4].innerHTML = "멀티컬러 섀도우"
        iprice[4].innerHTML = "SOLD OUT"
        iprice[4].style.color = "red"
        iprice[4].style.fontWeight = "bold"
        item2[1].style.display = "none"
        item2[2].style.display = "none"
        item2[3].style.display = "none"
        break;
    case "MASCARA":
        item_theme = "MASCARA"
        list_name.innerHTML = "MASCARA"
        item_code[0]="M_M1"
        img[0].src = "리스트이미지/마스카라1.jpg"
        iname[0].innerHTML = "볼륨 마스카라"
        iprice[0].innerHTML = "33,000원"
        item_code[1]="M_M2"
        img[1].src = "리스트이미지/마스카라2.jpg"
        iname[1].innerHTML = "롱 마스카라"
        iprice[1].innerHTML = "40,000원"
        item_code[2]="M_M3"
        img[2].src = "리스트이미지/마스카라3.jpg"
        iname[2].innerHTML = "슈퍼볼륨 마스카라"
        iprice[2].innerHTML = "35,000원"
        item_code[3]="M_M4"
        img[3].src = "리스트이미지/마스카라4.jpg"
        iname[3].innerHTML = "스키니 마스카라"
        iprice[3].innerHTML = "50,000원"
        img[4].src = "리스트이미지/마스카라5.jpg"
        iname[4].innerHTML = "투명 마스카라"
        iprice[4].innerHTML = "SOLD OUT"
        iprice[4].style.color = "red"
        iprice[4].style.fontWeight = "bold"
        img[5].src = "리스트이미지/마스카라6.jpg"
        iname[5].innerHTML = "워터프루프 마스카라"
        iprice[5].innerHTML = "SOLD OUT"
        iprice[5].style.color = "red"
        iprice[5].style.fontWeight = "bold"
        item2[2].style.display = "none"
        item2[3].style.display = "none"
        break;
    case "LIPSTICK":
        list_name.innerHTML = "LIPSTICK"
        img[0].src = "리스트이미지/립스틱1.jpg"
        iname[0].innerHTML = "헤라"
        iprice[0].innerHTML = "35,000원"
        img[1].src = "리스트이미지/립스틱2.jpg"
        iname[1].innerHTML = "맥"
        iprice[1].innerHTML = "30,000원"
        img[2].src = "리스트이미지/립스틱3.jpg"
        iname[2].innerHTML = "아르마니"
        iprice[2].innerHTML = "45,000원"
        img[3].src = "리스트이미지/립스틱4.jpg"
        iname[3].innerHTML = "샤넬"
        iprice[3].innerHTML = "55,000원"
        img[4].src = "리스트이미지/립스틱5.jpg"
        iname[4].innerHTML = "디올"
        iprice[4].innerHTML = "55,000원"
        img[5].src = "리스트이미지/립스틱6.jpg"
        iname[5].innerHTML = "슈에무라"
        iprice[5].innerHTML = "35,000원"
        img[6].src = "리스트이미지/립스틱7.jpg"
        iname[6].innerHTML = "바비 브라운"
        iprice[6].innerHTML = "SOLD OUT"
        iprice[6].style.color = "red"
        iprice[6].style.fontWeight = "bold"
        img[7].src = "리스트이미지/립스틱8.jpg"
        iname[7].innerHTML = "닉스"
        iprice[7].innerHTML = "SOLD OUT"
        iprice[7].style.color = "red"
        iprice[7].style.fontWeight = "bold"
        break;
    
    case "TINT":
        list_name.innerHTML = "TINT"
        img[0].src = "리스트이미지/틴트1.jpg"
        iname[0].innerHTML = "베네피트"
        iprice[0].innerHTML = "45,000원"
        img[1].src = "리스트이미지/틴트2.jpg"
        iname[1].innerHTML = "라네즈"
        iprice[1].innerHTML = "20,000원"
        img[2].src = "리스트이미지/틴트3.jpg"
        iname[2].innerHTML = "미샤"
        iprice[2].innerHTML = "11,000원"
        img[3].src = "리스트이미지/틴트4.jpg"
        iname[3].innerHTML = "웨이크메이크"
        iprice[3].innerHTML = "13,000원"
        img[4].src = "리스트이미지/틴트5.jpg"
        iname[4].innerHTML = "이니스프리"
        iprice[4].innerHTML = "SOLD OUT"
        iprice[4].style.color = "red"
        iprice[4].style.fontWeight = "bold"
        item2[1].style.display = "none"
        item2[2].style.display = "none"
        item2[3].style.display = "none"
        break;
    case "NEW":
        list_name.innerHTML = "NEW"
        list2.style.display = "none"
        img[0].src = "메인이미지/뉴1.png"
        iname[0].innerHTML = "벨벳 립 틴트"
        iprice[0].innerHTML = "60,000원"
        img[1].src = "메인이미지/뉴2.png"
        iname[1].innerHTML = "펜 아이라이너"
        iprice[1].innerHTML = "45,000원"
        img[2].src = "메인이미지/뉴3.png"
        iname[2].innerHTML = "글리터 아이라이너"
        iprice[2].innerHTML = "33,000원"
        img[3].src = "메인이미지/뉴4.png"
        iname[3].innerHTML = "립스틱"
        iprice[3].innerHTML = "65,000원"
        break;
    case "BEST":
        list_name.innerHTML = "BSET"
        list2.style.display = "none"
        img[0].src = "메인이미지/베스트1.png"
        iname[0].innerHTML = "섀도우"
        iprice[0].innerHTML = "45,000원"
        img[1].src = "메인이미지/베스트2.png"
        iname[1].innerHTML = "벨벳 핏틴트"
        iprice[1].innerHTML = "60,000원"
        img[2].src = "메인이미지/베스트3.png"
        iname[2].innerHTML = "파우더 팩트"
        iprice[2].innerHTML = "33,000원"
        img[3].src = "메인이미지/베스트4.png"
        iname[3].innerHTML = "오토젤 아이라이너"
        iprice[3].innerHTML = "81,000원"
        break;
    case "LIPCARE":
        list_name.innerHTML = "LIPCARE"
        list1.style.display = "none"
        list2.style.display = "none"
        no.style.display = "block"
        break;
    case "BLUSH":
        list_name.innerHTML = "BLUSH"
        list1.style.display = "none"
        list2.style.display = "none"
        no.style.display = "block"
        break;
    case "CONTOUR":
        list_name.innerHTML = "CONTOUR"
        list1.style.display = "none"
        list2.style.display = "none"
        no.style.display = "block"
        break;
    case "HIGHLIGHT":
        list_name.innerHTML = "HIGHLIGHT"
        list1.style.display = "none"
        list2.style.display = "none"
        no.style.display = "block"
        break;
}